### ISSUE TITLE
MM2 Split on teleport does not work with Nestopia

### ISSUE THREAD

**Issue by HyperFluxQc** [Coltaho/Autosplitters#17]
I suppose the split on teleport use the SFX to trigger...
in state("nestopia"), the lines : 
	byte soundfx : "nestopia.exe", 0x1b2bcc, 0, 8, 0xc, 0xc, 0xE2;
	byte stage : "nestopia.exe", 0x1b2bcc, 0, 8, 0xc, 0xc, 0x2A;
are missing the 0x68 offset, to make it work, it must be : 
	byte soundfx : "nestopia.exe", 0x1b2bcc, 0, 8, 0xc, 0xc, 0x14a;
	byte stage : "nestopia.exe", 0x1b2bcc, 0, 8, 0xc, 0xc, 0x92;

**Comment by Coltaho** [comment]
Could catch - I've never actually used Nestopia. Resolved.
