### ISSUE TITLE
Add support for new version 1.57 of Snes9x

### ISSUE THREAD

**Issue by sharivan** [Coltaho/Autosplitters#4]
Hello again.

Recently was released a new version 1.57 for Snes9x emulator, but unfortunately the Autosplitter doesnt recognize this new version. Please add support to this new version;

**Comment by Coltaho** [comment]
Nice! Didn't know it was out yet. I'll look into it.

**Comment by Coltaho** [comment]
All 3 scripts (MMX, MMX2, and TMNT4) should now be updated to support 1.57 32 and 64-bit.

**Comment by sharivan** [comment]
Thks very much;
